apiVersion: v1
kind: Service
metadata:
  name: payoffgenerator
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: payoffgenerator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80